// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/dnscircuit/config.proto

package dnscircuit

import (
	geodata "github.com/xtls/xray-core/common/geodata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InboundTags     []string               `protobuf:"bytes,1,rep,name=inbound_tags,json=inboundTags,proto3" json:"inbound_tags,omitempty"`
	OutboundTags    []string               `protobuf:"bytes,2,rep,name=outbound_tags,json=outboundTags,proto3" json:"outbound_tags,omitempty"`
	BalancerTags    []string               `protobuf:"bytes,3,rep,name=balancer_tags,json=balancerTags,proto3" json:"balancer_tags,omitempty"`
	DnsOutboundTag  string                 `protobuf:"bytes,4,opt,name=dns_outbound_tag,json=dnsOutboundTag,proto3" json:"dns_outbound_tag,omitempty"`
	InactiveClean   int64                  `protobuf:"varint,5,opt,name=inactive_clean,json=inactiveClean,proto3" json:"inactive_clean,omitempty"`
	OspfSetting     *OSPFInstanceConfig    `protobuf:"bytes,6,opt,name=ospf_setting,json=ospfSetting,proto3" json:"ospf_setting,omitempty"`
	PersistentRoute []*geodata.IPRule      `protobuf:"bytes,7,rep,name=persistent_route,json=persistentRoute,proto3" json:"persistent_route,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_dnscircuit_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_dnscircuit_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_dnscircuit_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetInboundTags() []string {
	if x != nil {
		return x.InboundTags
	}
	return nil
}

func (x *Config) GetOutboundTags() []string {
	if x != nil {
		return x.OutboundTags
	}
	return nil
}

func (x *Config) GetBalancerTags() []string {
	if x != nil {
		return x.BalancerTags
	}
	return nil
}

func (x *Config) GetDnsOutboundTag() string {
	if x != nil {
		return x.DnsOutboundTag
	}
	return ""
}

func (x *Config) GetInactiveClean() int64 {
	if x != nil {
		return x.InactiveClean
	}
	return 0
}

func (x *Config) GetOspfSetting() *OSPFInstanceConfig {
	if x != nil {
		return x.OspfSetting
	}
	return nil
}

func (x *Config) GetPersistentRoute() []*geodata.IPRule {
	if x != nil {
		return x.PersistentRoute
	}
	return nil
}

type OSPFInstanceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IfName        string                 `protobuf:"bytes,1,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	Address       *geodata.CIDR          `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFInstanceConfig) Reset() {
	*x = OSPFInstanceConfig{}
	mi := &file_app_dnscircuit_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFInstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFInstanceConfig) ProtoMessage() {}

func (x *OSPFInstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_dnscircuit_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFInstanceConfig.ProtoReflect.Descriptor instead.
func (*OSPFInstanceConfig) Descriptor() ([]byte, []int) {
	return file_app_dnscircuit_config_proto_rawDescGZIP(), []int{1}
}

func (x *OSPFInstanceConfig) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *OSPFInstanceConfig) GetAddress() *geodata.CIDR {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_app_dnscircuit_config_proto protoreflect.FileDescriptor

const file_app_dnscircuit_config_proto_rawDesc = "" +
	"\n" +
	"\x1bapp/dnscircuit/config.proto\x12\x13xray.app.dnscircuit\x1a\x1bcommon/geodata/geodat.proto\"\xda\x02\n" +
	"\x06Config\x12!\n" +
	"\finbound_tags\x18\x01 \x03(\tR\vinboundTags\x12#\n" +
	"\routbound_tags\x18\x02 \x03(\tR\foutboundTags\x12#\n" +
	"\rbalancer_tags\x18\x03 \x03(\tR\fbalancerTags\x12(\n" +
	"\x10dns_outbound_tag\x18\x04 \x01(\tR\x0ednsOutboundTag\x12%\n" +
	"\x0einactive_clean\x18\x05 \x01(\x03R\rinactiveClean\x12J\n" +
	"\fospf_setting\x18\x06 \x01(\v2'.xray.app.dnscircuit.OSPFInstanceConfigR\vospfSetting\x12F\n" +
	"\x10persistent_route\x18\a \x03(\v2\x1b.xray.common.geodata.IPRuleR\x0fpersistentRoute\"b\n" +
	"\x12OSPFInstanceConfig\x12\x17\n" +
	"\aif_name\x18\x01 \x01(\tR\x06ifName\x123\n" +
	"\aaddress\x18\x02 \x01(\v2\x19.xray.common.geodata.CIDRR\aaddressB[\n" +
	"\x17com.xray.app.dnscircuitP\x01Z(github.com/xtls/xray-core/app/dnscircuit\xaa\x02\x13Xray.App.DnsCircuitb\x06proto3"

var (
	file_app_dnscircuit_config_proto_rawDescOnce sync.Once
	file_app_dnscircuit_config_proto_rawDescData []byte
)

func file_app_dnscircuit_config_proto_rawDescGZIP() []byte {
	file_app_dnscircuit_config_proto_rawDescOnce.Do(func() {
		file_app_dnscircuit_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_dnscircuit_config_proto_rawDesc), len(file_app_dnscircuit_config_proto_rawDesc)))
	})
	return file_app_dnscircuit_config_proto_rawDescData
}

var file_app_dnscircuit_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_dnscircuit_config_proto_goTypes = []any{
	(*Config)(nil),             // 0: xray.app.dnscircuit.Config
	(*OSPFInstanceConfig)(nil), // 1: xray.app.dnscircuit.OSPFInstanceConfig
	(*geodata.IPRule)(nil),     // 2: xray.common.geodata.IPRule
	(*geodata.CIDR)(nil),       // 3: xray.common.geodata.CIDR
}
var file_app_dnscircuit_config_proto_depIdxs = []int32{
	1, // 0: xray.app.dnscircuit.Config.ospf_setting:type_name -> xray.app.dnscircuit.OSPFInstanceConfig
	2, // 1: xray.app.dnscircuit.Config.persistent_route:type_name -> xray.common.geodata.IPRule
	3, // 2: xray.app.dnscircuit.OSPFInstanceConfig.address:type_name -> xray.common.geodata.CIDR
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_dnscircuit_config_proto_init() }
func file_app_dnscircuit_config_proto_init() {
	if File_app_dnscircuit_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_dnscircuit_config_proto_rawDesc), len(file_app_dnscircuit_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_dnscircuit_config_proto_goTypes,
		DependencyIndexes: file_app_dnscircuit_config_proto_depIdxs,
		MessageInfos:      file_app_dnscircuit_config_proto_msgTypes,
	}.Build()
	File_app_dnscircuit_config_proto = out.File
	file_app_dnscircuit_config_proto_goTypes = nil
	file_app_dnscircuit_config_proto_depIdxs = nil
}
